name: spd_reeig_relu_15
architecture:
    - BiMap:
          args: [116, 15]
    - ReEig:
          eps: 0.1
    - ReLU:
    - LogEig:
    - FlattenSPD:
          args: [15]
    - Linear:
          args: [120, 1]
