name: spd_relu_reeig_15
architecture:
    - BiMap:
          args: [116, 15]
    - ReLU:
    - ReEig:
          eps: 0.1
    - LogEig:
    - FlattenSPD:
          args: [15]
    - Linear:
          args: [120, 1]
